### ISSUE TITLE
Can we change sources to be relative to file.cwd instead of file.base?

### ISSUE THREAD

**Issue by rhendric** [floridoo/gulp-sourcemaps#175] opened 2016-01-02 22:24 UTC
Consider this gulp pipeline:

``` js
gulp.src('src/**/*.js')
  .pipe(sourcemaps.init())
    .pipe(plugin1())
    .pipe(gulp.dest('generated'))
    .pipe(plugin2())
  .pipe(sourcemaps.write())
  .pipe(gulp.dest('dist'));
```

The intent is to save the intermediate files produced by plugin1, while still forwarding them on to plugin2. However, this pipeline produces faulty sourcemaps, because when `sourcemaps.write()` looks up the original sources, it looks for them in `generated` instead of in `src`. It does this because it assumes that source map sources are relative to `file.base`, and `gulp.dest` changes `file.base` from `'src'` to `'generated'`.

I've thought of a few possible workarounds for this but all of them are unsatisfactory in some way:
##### Force `base` to be `'.'`

This seems to be the go-to fix for confusing path problems in gulp: just add `{ base: '.' }` to the `gulp.src` call and have everything be on the same playing field. Additional care is still needed to rebase the file after the `gulp.dest('generated')` element, so it's not very elegant. Worse, some plugins use the relative paths of their input files as information for, _e.g._, module import lookups, and changing the base means changing these semantics.
##### Explicitly specify a `sourceRoot`

On the other end, adding `{ sourceRoot: 'src' }` to the `sourcemaps.write` call would fix this pipeline, but this assumes that all sources come from the same root. In a more complicated pipeline involving multiple source directories being merged together—a `src` and a `lib`, say—this wouldn't work.
##### Propose changes to `gulp.dest`

You might argue that the problem here is with the base changing, not with gulp-sourcemaps's handling.
I could replace `gulp.dest` with a function that doesn't change `base`, or that also rewrites the `sources` attribute on any source maps that are attached to files coming in. Or I could propose to the gulp project that one of these behaviors ought to be adopted. The trouble here is that there are many other plugins that change the `path` attribute on files, and all of them would need to do the same thing to be consistent.

So here's what I'm proposing: Change the behavior in `sourcemaps.write` to use `file.cwd` as the assumed base directory instead of `file.base` when looking up source contents, and make this always be used regardless of `sourceRoot`. Concurrently, change [vinyl-sourcemaps-apply](/floridoo/vinyl-sourcemaps-apply) to prepend `file.base` (technically, just the part relative to `file.cwd`) to each of the paths in `sources` on the source map that is passed to it. This way, plugins that generate source maps can continue to do so relative to `file.base`, which makes sense because they generally work with just the `file.relative` part of the path anyway.  Gulp pipelines that have been written with either of the first two workarounds would continue to work just fine—in the first, `base` equals `cwd` so this is a no-op, and in the second, the `sourceRoot` no longer affects source lookup. And since pipelines don't change the working directory, the source paths are now correct regardless of how many other elements manipulate the files.

Note, I'm just talking about the source map data as it's passed around between `init` and `write`, not the written source map itself. The folks working on #156, #157, and #163 would probably need to take this into account when they make the _written_ `file` and `sources` properties relative to the written location instead of what they currently are, but I don't think either is a requirement for the other.

Is this reasonable? I can put together a PR if so.

**Comment by phated** [comment] 2017-03-13 22:09
This is intended behavior (in `gulp.dest` and here from what I can tell).  You can do a map over the stream if you need to change base.  Going to close this.

**Closed by phated** 2017-03-13 22:09 UTC
