### ISSUE TITLE
Different directories without changing the src base

### ISSUE THREAD

**Issue by errorx666** [floridoo/gulp-sourcemaps#265] opened 2016-12-29 18:55 UTC
From the README.md:

#### Handle source files from different directories

Use the `base` option on `gulp.src` to make sure all files are relative to a common base directory.

Example:
```javascript
var gulp = require('gulp');
var plugin1 = require('gulp-plugin1');
var plugin2 = require('gulp-plugin2');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('javascript', function() {
gulp.src(['src/test.js', 'src/testdir/test2.js'], { base: 'src' })
    .pipe(sourcemaps.init())
      .pipe(plugin1())
      .pipe(plugin2())
    .pipe(sourcemaps.write('../maps'))
    .pipe(gulp.dest('dist'));
});
```

Unfortunately, I have two directories containing input files, but both subtrees have the same destination.  I can't set `base` here because that will change where the compiled files go, and how they reference each other.

My use case is an isomorphic TypeScript application.  There are two build tasks: one builds `[ 'shared/**/*.ts', 'client/**/*.ts' ]` and one builds `[ 'shared/**/*.ts', 'server/**/*.ts' ]`.  The `shared` folder contains the code common to both client and server.  This is transparent to the TypeScript build - it doesn't know or care that the files are coming from two different directories... but it's relevant information for the source maps.

The output directory does not contain a `shared`, `client`, or `server` folder - so setting the `base` option would change (break) the output.

Is it possible to support this use-case?

Actual build tasks:
```js
gulp.task( 'build:ts:client', () => {
	const tsproj = typescript.createProject( 'client/tsconfig.json' );
	return gulp.src( [
		'ts/**/*.ts',
		'client/ts/**/*.ts'
	] )
	.pipe( sourcemaps.init() )
	.pipe( tsproj() )
	.pipe( gulpIf( options.babel, babel( { presets: [ 'es2015' ] } ) ) )
	.pipe( sourcemaps.write( './', { includeContent: false } ) )
	.pipe( gulp.dest( 'client/js' ) );
} );

gulp.task( 'build:ts:server', () => {
	const tsproj = typescript.createProject( 'server/tsconfig.json' );
	return gulp.src( [
		'ts/**/*.ts',
		'server/ts/**/*.ts'
	] )
	.pipe( sourcemaps.init() )
	.pipe( tsproj() )
	.pipe( sourcemaps.write( './', { includeContent: false } ) )
	.pipe( gulp.dest( 'server/js' ) );
} );
```

**Comment by nmccready** [comment] 2017-01-08 19:56
To understand your use case better you basically are trying to reduce this to one gulp task instead of the two correct? To visually see what is wrong with using base could you please create a mock project in a repo to run gulp against?  You could also write an integration test in this project to show explicit fails. This way I can understand exactly why `base` will not work for you.

**Comment by phated** [comment] 2017-03-13 22:36
Closing as a duplicate of any/all of the typescript issues on this repo.  Support questions should be directed to StackOverflow.

**Closed by phated** 2017-03-13 22:36 UTC

**Comment by errorx666** [comment] 2017-03-14 14:02
@phated OK, but it was more of a feature request for gulp-sourcemaps to support a scenario where files come from disparate sources.
