### ISSUE TITLE
Error: Cannot find module './src/init'

### ISSUE THREAD

**Issue by slahav** [floridoo/gulp-sourcemaps#243] opened 2016-10-13 21:19 UTC
Getting this error while running `npm install`
this just started happening on multiple projects all at once. anybody been experiencing that as well? 

`Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sivan lahav/dev/projects/digit-ifabric/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)`

**Comment by thompk2** [comment] 2016-10-13 21:21
This looks like a dupe of this: https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by jtragg** [comment] 2016-10-13 21:21
already reported, see #238

Fix your version to 1.7.x while they work on a fix

**Comment by slahav** [comment] 2016-10-13 21:22
its coming as a dependency of karma-sourcemap-loader@0.3.7 ...

**Comment by toddlucas** [comment] 2016-10-13 21:22
Yes, we're stuck since it's a dependency of another module.

**Comment by jtragg** [comment] 2016-10-13 21:24
🤕

**Comment by sbalay** [comment] 2016-10-13 21:32
Same here, can not init a react native project because of this issue.
```
$ react-native init project
This will walk you through creating a new React Native project in /Users/user/project
Installing react-native package from npm...
Setting up new React Native app in /Users/user/project
module.js:327
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/user/project/node_modules/react-native/node_modules/yeoman-generator/node_modules/download/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/project/node_modules/react-native/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by aredridel** [comment] 2016-10-13 21:39
same thing happens with the npm website, actually! Looks like the module was incompletely published?

**Comment by bcherny** [comment] 2016-10-13 21:44
@nmccready Maybe you could fix the issue instead of locking the conversation and going to the gym 👎

**Comment by luisvt** [comment] 2016-10-13 21:47
Looks like this pull request is the soulution:
https://github.com/floridoo/gulp-sourcemaps/pull/244

**Comment by steinbergkh** [comment] 2016-10-13 21:48
@toddlucas npm shrinkwrap? https://docs.npmjs.com/cli/shrinkwrap

**Comment by toddlucas** [comment] 2016-10-13 21:49
Thanks @steinbergkh !

**Comment by elgambet** [comment] 2016-10-13 21:51
As @jtragg said, already reported, see [#238](https://github.com/floridoo/gulp-sourcemaps/issues/238)

For the time being lock your version down to 2.0.x or 1.7.x

**Comment by navels** [comment] 2016-10-13 22:02
Locking down to 1.7.x fixed it for us.  We also did not have an explicit dependency on gulp-sourcemaps so just added one.

Now we have to get all our developer branches sync-ed up with default.  Our TeamCity dashboard is very red right now.

**Comment by phated** [comment] 2016-10-13 22:08
gulp 4 has locked gulp-sourcemaps to 1.6 in vinyl-fs 2.4.4 because that is the version we've been using forever before the project started having breaking releases every couple of days.  We are in the process of removing gulp-sourcemaps from our dependency tree.

**Comment by aredridel** [comment] 2016-10-13 22:08
One thing that can help with this in the future is unpublishing a known-completely-broken version right away. This one falls within our 24-hour window, so would have been allowed, and solved the immediate breakage.

**Comment by phated** [comment] 2016-10-13 22:09
@aredridel the gulp team doesn't control this package and the original maintainer is no longer active, which is why we've decided to move away from the dependency.

**Comment by KeatsPeeks** [comment] 2016-10-13 22:20
So many projects regularly broken by this in the last couple days. 
Locking to 1.6 seems to be a good idea for the time being.

**Comment by ddvorak** [comment] 2016-10-13 22:23
Just had this break our builds, locked it down to 1.6, committed the change to our package.json with the message: "ILL FIX IT WHEN I GET BACK FROM THE GYM"

**Comment by nmccready** [comment] 2016-10-13 22:25
I am working on it now, if anyone wants to truley help we can hop on a hangout.

**Comment by nmccready** [comment] 2016-10-13 22:25
@phated anyway I can chat w/ u?

**Comment by nmccready** [comment] 2016-10-13 22:29
2.1.1 released and 1.8.1

**Closed by nmccready** 2016-10-13 22:29 UTC

**Comment by nmccready** [comment] 2016-10-13 22:40
#238 orig

**Comment by nmccready** [comment] 2016-10-13 22:41
> the original maintainer is no longer active, which is why we've decided to move away from the dependency.

@phated this is exactly why I have been working on this project to get it moving. I would add others to the project to fix crap that just happend.. but I do not have the perms to do so. @floridoo we need more admins.

**Comment by PWKad** [comment] 2016-10-13 22:45
@nmccready Thanks for this, confirmed working on Aurelia cli project

**Comment by hrickards** [comment] 2016-10-13 22:46
Thank you @nmccready!!

**Comment by nmccready** [comment] 2016-10-13 22:47
Now here is a real question where I am looking for some constructive advice. I would have never pushed this problem if it would have been caught on travis or on local specs. So are there any mock npm publishing / integration specs that anyone already has to avoid this kind of disaster again?

**Comment by PWKad** [comment] 2016-10-13 22:48
Hmm I guess you could link it in a script and install it or set up a free sinopia server (if there is such a thing) on CI to test?

**Comment by PWKad** [comment] 2016-10-13 22:49
BTW if you are the owner I think you can fork this, change the source location in package.json, and start pushing from a new repository (or ask the current owner or npm to transfer if you can show that you are the lead maintainer now)

**Comment by nmccready** [comment] 2016-10-13 22:51
@bcherny
> @nmccready Perhaps it would be more productive to help fix the issue than to lock the conversation and go to the gym

Perhaps it would be more constructive if you just leaved existing issues as is and do thumbs up. Why do you think I locked it? I am getting spammed with emails. Why do you think @floridoo isn't responding? Again, (this is a guess) he is sick of the emails I am sure.

I don't want to start a fight, but this kind of stuff is what leads to absolute burn out. I am trying to help. But instead I am getting crucified.

**Comment by nmccready** [comment] 2016-10-13 22:53
@PWKad cool any examples or psuedo code to mock in a gist?

**Comment by usirin** [comment] 2016-10-13 22:56
> I don't want to start a fight, but this kind of stuff is what leads to absolute burn out. I am trying to help. But instead I am getting crucified.

@nmccready it's probably because of the fact that all of us are burned out already and when "I'll fix it after gym" it immediately annoys the other people who read. 

People (at least me) is annoyed by the attitude of the response when they saw their build is broken without doing anything when they came here to seek for a help and saw that.

**Comment by usirin** [comment] 2016-10-13 22:58
But anyway, thank you so much for fixing it.

**Comment by nmccready** [comment] 2016-10-13 22:59
@aredridel
> One thing that can help with this in the future is unpublishing a known-completely-broken version right away. This one falls within our (npm's) 24-hour window, so would have been allowed, and solved the immediate breakage.

When I got home I thought about doing this, when I was in panic mode. I wasn't positive if that was a good approach, but next time (god forbid) I will do that first.

**Comment by PWKad** [comment] 2016-10-13 23:01
I would expect a shell script like this to work - 

```shell
$ cd {source folder}
$ npm link
$ cd ..
$ mkdir test
$ npm link gulp-sourcemaps
```

 I think if you run that on Travis and it fails the build would fail but I'd have to test that.

**Comment by nmccready** [comment] 2016-10-13 23:01
@usirin

> @nmccready it's probably because of the fact that all of us are burned out already and when "I'll fix it after gym" it immediately annoys the other people who read.
> 
> People (at least me) is annoyed by the attitude of the response when they saw their build is broken without doing anything when they came here to seek for a help and saw that.

Your attitude is misread. Do you want me to respond with a full paragraph and some cliff-notes when I am stopped at a stop light? 

Anyway, I was trying to respond to acknowledge the problem ASAP to limit the spam.

**Comment by nmccready** [comment] 2016-10-13 23:02
@PWKad cool i will give that shot by going back to broke code and see if fails on running those commands.

**Comment by bcherny** [comment] 2016-10-13 23:09
> Perhaps it would be more constructive if you just leaved existing issues as is and do thumbs up. Why do you think I locked it? I am getting spammed with emails. Why do you think @floridoo isn't responding? Again, (this is a guess) he is sick of the emails I am sure and I bet he is unsubscribed from the repo.

I know it sucks, but when people depend on your project and you break it, they expect you to fix it as soon as you possibly can. With the number of people whose builds you broke (accidentally, to be clear), I expect an immediate response - not "i'll do it later". I get that we're not paid to do this, but that doesn't mean we don't owe users an immediate response.

In this case, the response should have been a git revert + republish, or unpublish, until you could figure out what the issue was.

For me, all of my team's builds broke, and we were unable to deploy any code. So I had to spend time digging into what dependency broke, if it recently updated, what was the last new version, etc. We should have shrink-wrapped our dev-dependencies (we only shrinkwrapped our prod dependencies before), and now we are, but it sucks to not be able to depend on semver because of stuff like this.

**Comment by nmccready** [comment] 2016-10-13 23:11
@bcherny that was ASAP I have a life beyond code. For the record, I did give you an immediate response. Guess I need to figure out how to unpublished from my phone.

**Comment by nmccready** [comment] 2016-10-13 23:12
eh. locking as this is going to go nowhere like a Trump and Hilary debate.
