### ISSUE TITLE
Node V6 error - 'Path must be a string. Received undefined'

### ISSUE THREAD

**Issue by Gobd** [floridoo/gulp-sourcemaps#192] opened 2016-04-27 16:44 UTC
Receiving error 'Path must be a string. Received undefined' when running with Node V6. This Gulp task worked fine with Node V5.11.0. Using gulp-sourcemaps v2.0.0-alpha

``` javascript
gulp.task('stylus', function () {
     return gulp.src('src/**/*.styl')
        .pipe(flatten())
        .pipe(sourcemaps.init())
        .pipe(stylus({use: rupture()}))
        .pipe(plumber())
        .pipe(uncss({html: ['src/**/*.html']}))
        .pipe(cleanCSS())
        .pipe(postcss(processors))
        .pipe(concat('css.min.css'))
        .pipe(sourcemaps.write('/maps'))
        .pipe(gulp.dest('./dist/css'))
        .pipe(reload({stream: true, match: '**/*.css'}));
});
```

Task works fine when I comment out both sourcemap lines.

**Comment by seanmcintyre** [comment] 2016-04-28 14:10
`throw new TypeError('Path must be a string. Received ' + inspect(path));`

**Comment by Gobd** [comment] 2016-04-28 14:39
Looks like [this issue](https://github.com/nodejs/node/pull/5348) might be the cause of this problem.

**Comment by stevesloan** [comment] 2016-05-21 04:22
[This pull request](https://github.com/jakubpawlowicz/clean-css/pull/774)  solves the problem.

**Comment by codecakes** [comment] 2016-06-03 08:42
getting same error here

**Comment by mbrevda** [comment] 2016-08-11 08:51
@stevesloan how does that pull request solve the issue? What would I need to do?

**Comment by insanityfarm** [comment] 2016-08-12 18:03
It's been [merged into clean-css at version 3.4.13](https://github.com/jakubpawlowicz/clean-css/pull/774#issuecomment-220938685). So you should get the fix if your version is newer than that. You can run `npm view clean-css version` to see what version you currently have installed.

**Comment by StealthyDev** [comment] 2016-08-23 14:57
Can you tell me how to upgrade the clean-css?

I am running the latest release version of Node.

![image](https://cloud.githubusercontent.com/assets/2009963/17896948/61dd8e52-6920-11e6-9224-19130f93c332.png)

**Comment by insanityfarm** [comment] 2016-08-23 15:53
You should be able to run `npm update clean-css` to fetch the most recent release.

**Comment by StealthyDev** [comment] 2016-08-23 15:55
still i receive the same error. could be some other issue?

**Comment by nmccready** [comment] 2016-10-10 18:43
@StealthyDev what is the result of this running against master?

**Comment by Rand0mGuy** [comment] 2016-11-10 15:49
I got an error too.

`path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { includePaths:
   [ './node_modules/foundation-sites/scss',
     './node_modules/motion-ui/src' ] }
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at prefixOne (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:143:43)
    at GulpPaths.prefix (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:153:20)
    at GulpPaths.src (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\tasks\GulpPaths.js:44:25)
    at getPaths (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\tasks\recipes\sass.js:33:33)
    at Function.<anonymous> (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\tasks\recipes\sass.js:21:33)
    at Function.<anonymous> (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\bootstrap\EnableExtension.js:16:18)
    at mix (D:\WAMP\www\Project\LFTest\gulpfile.js:23:9)
    at global.Elixir (D:\WAMP\www\Project\LFTest\node_modules\laravel-elixir\dist\index.js:21:5)
`
Any help?

**Comment by nmccready** [comment] 2016-12-01 05:26
If this is still a problem please produce an example like [this](https://github.com/floridoo/gulp-sourcemaps/issues/248#issuecomment-264068633).

Or add integration or unit specs to the 1.X branch that causes this error to happen.

**Comment by nmccready** [comment] 2016-12-01 05:27
Closing unless someone else produces something to work with as clean-css seemed to be the main problem.

**Closed by nmccready** 2016-12-01 05:27 UTC

**Comment by Mashqur** [comment] 2017-02-02 09:39
I have one project which is running but the new one is not running. Facing this error. If node version is the cause then older app should not run right? I am getting confused. Because in my machine node version is 6.X.X

**Comment by nmccready** [comment] 2017-02-02 20:50
@Mashqur can you produce a small example which can be used in https://github.com/floridoo/gulp-sourcemaps/blob/master/test/integration.js and https://github.com/floridoo/gulp-sourcemaps/blob/master/test/assets ? 

You can PR the spec to a different branch, and or pack up a zip and I can manual merge in the specs.

**Comment by nmccready** [comment] 2017-02-02 20:51
If anyone make an example to test in integration.js please make sure it is branched off 1.X branch as it is easy to roll changes up to master.

**Comment by cpbotha** [comment] 2017-06-25 15:07
I ran into exactly this issue over here with an old app I needed to update.

You should be able to fix it by doing: `npm upgrade gulp-clean-css`

**Comment by dvdobrovolskiy** [comment] 2017-07-31 12:19
have same issue

**Comment by gekannt** [comment] 2017-09-20 12:45
me too

**Comment by joarobles** [comment] 2017-11-03 13:29
same here

**Comment by gubenkovalik** [comment] 2017-11-06 10:16
СУКА ПИДАРАСЫ БЛЯТЬ

**Comment by pmstss** [comment] 2018-04-28 09:45
For me same error happened with node v10.0.0, gulp-sourcemaps 2.6.4, gulp-babel 7.0.1 and was caused by inlined map (//# sourceMappingURL=data:application/json;charset:utf-8;base64,...) at the end of one of the third party library js file
