### ISSUE TITLE
Incorrect maps produced for gulp-typescript & gulp-react

### ISSUE THREAD

**Issue by levibotelho** [floridoo/gulp-sourcemaps#211] opened 2016-07-15 16:22 UTC
I have the following Gulp task

```
gulp.task("compile-javascript", function () {
    const tsconfig = require("./tsconfig.json").compilerOptions;
    return gulp.src(TS_SOURCE, {base: "."})
        .pipe(addSrc(TS_DEFINITIONS_SOURCE))
        .pipe(sourcemaps.init())
        .pipe(ts(tsconfig))
        .pipe(react())
        .pipe(sourcemaps.write("./"))
        .pipe(gulp.dest(TS_COMPILE_PATH));
});
```

When I compile a file that looks like this

```
export default class ErrorMessage extends React.Component<ErrorMessageState, {}> {
    render() {
        return this.props.hidden ? <span></span> :
            (
                <div className="row">
                    <div className="col-xs-12">
                        <div className="alert alert-danger" role="alert">
                            {this.props.message}
                        </div>
                    </div>
                </div>
            );
    }
}
```

I get the following sourcemap

```
{"version":3,"sources":["js/components/error-message.jsx"],"names":[],"mappings":"AAAA,YAAY,CAAC;AACb,MAAM,KAAK,GAAG,OAAO,CAAC,OAAO,CAAC,CAAC;AAC/B,MAAM,YAAY,SAAS,KAAK,CAAC,SAAS,CAAC;IACvC,MAAM,GAAG;QACL,OAAO,IAAI,CAAC,KAAK,CAAC,MAAM,GAAG,oBAAA,MAAK,EAAA,IAAQ,CAAA;aACnC,oBAAA,KAAI,EAAA,CAAA,CAAC,SAAA,EAAS,CAAC,KAAM,CAAA,EAAA;oBACd,oBAAA,KAAI,EAAA,CAAA,CAAC,SAAA,EAAS,CAAC,WAAY,CAAA,EAAA;wBACvB,oBAAA,KAAI,EAAA,CAAA,CAAC,SAAA,EAAS,CAAC,oBAAA,EAAoB,CAAC,IAAA,EAAI,CAAC,OAAQ,CAAA,EAAA;4BAC5C,IAAI,CAAC,KAAK,CAAC,OAAQ;wBAClB,CAAA;oBACJ,CAAA;gBACJ,CAAA,CAAC,CAAC;KACnB;CACJ;AACD,MAAM,CAAC,cAAc,CAAC,OAAO,EAAE,YAAY,EAAE,EAAE,KAAK,EAAE,IAAI,EAAE,CAAC,CAAC;AAC9D,OAAO,CAAC,OAAO,GAAG,YAAY,CAAC","file":"js/components/error-message.js","sourcesContent":[null],"sourceRoot":"/source/"}
```

It appears that instead of combining the sourcemaps generated at the `gulp-typescript` step and the `gulp-react` step, it just takes the map from the `gulp-react` step which contains virtually no information, and points to a nonexistent file `error-message.jsx` which would have been created at the TypeScript step.

`gulp-sourcemaps` should combine the map produced at the TypeScript stage with that produced at the React stage and produce a single sourcemap containing all of the relevant information, should it not?

**Comment by phated** [comment] 2017-03-13 22:31
Closing this as a duplicate of one of the many typescript issues open on this repo.

**Closed by phated** 2017-03-13 22:31 UTC
