### ISSUE TITLE
sourcemaps.write adds null to the end of sourceMappingUrl

### ISSUE THREAD

**Issue by marcelombc** [floridoo/gulp-sourcemaps#233] opened 2016-10-11 10:38 UTC
The following task adds a null to the sourceMappingUrl when building in prod.

```
browserify({ entries: 'app/main.js', debug: true })
        .external(dependencies)
        .transform(babelify, { presets: ['es2015', 'react'] })
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(sourcemaps.init({ loadMaps: true }))
        .pipe(gulpif(argv.prod, stripDebug()))
        .pipe(gulpif(argv.prod, uglify({ mangle: false })))
        .pipe(sourcemaps.write('.',))
        .pipe(gulp.dest('public/js'));
```

`sourcemaps.write('.')` will output `//# sourceMappingURL=bundle.js.mapnull` to the end of the bundle.js file.
This only happens when the task runs the uglify.

**Comment by shinnn** [comment] 2016-10-11 10:44
Duplicate of https://github.com/floridoo/gulp-sourcemaps/issues/230

**Closed** 2016-10-11 13:16 UTC
Labels: duplicate
