### ISSUE TITLE
//@ sourceURL' and '//@ sourceMappingURL' are deprecated

### ISSUE THREAD

**Issue by throrin19** [floridoo/gulp-sourcemaps#220] opened 2016-08-23 09:55 UTC
Hello, I think the sourcemap library must to be upgraded to use the new sourceUrl format. In Chrome, I have this warning : 

```
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
```

**Comment by shinnn** [comment] 2016-08-23 09:56
Duplicate of https://github.com/floridoo/gulp-sourcemaps/issues/182

**Comment by nmccready** [comment] 2016-10-10 17:40
@shinnn since the dupe is closed, can this be closed?

**Closed** 2016-10-13 13:28 UTC
