### ISSUE TITLE
TypeScript debugging experience in Visual Studio

### ISSUE THREAD

**Issue by rendmath** [floridoo/gulp-sourcemaps#205] opened 2016-06-28 11:17 UTC
The Visual Studio TypeScript tools generate a sourcemap that is optimal in Visual Studio, because it not only allows you to debug from Visual Studio with Internet Explorer, but the file that opens when a breakpoint is hit is the actual .ts file, and not a "purple" (dynamic) tab. It allows for a very productive "Edit, F5 and continue" development experience.

For it to work, the map file must have this precise structure, and no variation seems to be working: the source files must be specified relative to the output path, and the sourceRoot has to be "" (the empty string). Therefore, I'm trying to reproduce this exact same result with gulp-sourcemaps.

`{"version":3,"file":"app.js","sourceRoot":"","sources":["../app/file1.ts","../app/file3.ts","../app/file2.ts"],"names":[],"mappings":"..."}`

Here is what I managed to accomplish until now:

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "module": "system",
    "outFile": "wwwroot/app.js"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

```
var tsProject = ts.createProject('tsconfig.json', { sortOutput: true });
    var tsResult = tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject));

    return tsResult.js
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('wwwroot/app'));
```

But it gives me this map file, which doesn't event hit any breakpoint:

```
{"version":3,"sources":["file1.ts","file3.ts","file2.ts"],"names":[],"mappings":"...","file":"app.js","sourceRoot":"app"}
```

I have tried all kinds of combinations with destPath, sourceRoot, etc. in 1.6.0 and 2.0.0, but nothing seems to deliver the expected result.

Any idea?

**Comment by rendmath** [comment] 2016-06-29 20:05
After reading the gulp-sourcemaps source code, we devised this solution that seems to match all our criteria (buildable from Visual Studio TypeScript integration or from gulp with identical results + live file debugging in Visual Studio). It overrides the tsconfig outFile, forces an empty sourceRoot, and prefixes all the sources with the relative path from the output file to the TypeScript application root.

Let's hope someone else will find it useful.
```
var tsProject = ts.createProject('tsconfig.json', { outFile: 'app.js'  });

gulp.task('scripts', function () {


    function prefixSources(prefix) {
        function process(file, encoding, callback) {

            if (file.sourceMap) {
                for (i in file.sourceMap.sources) {
                    var source = file.sourceMap.sources[i];
                    file.sourceMap.sources[i] = prefix + source;
                }
            }

            this.push(file);
            return callback();
        }

        return through.obj(process);
    }

    var tsResult = tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(ts(tsProject));

    return tsResult.js
        .pipe(prefixSources('../../app/'))
        .pipe(sourcemaps.write('.', { sourceRoot: '', includeContent: false }))
        .pipe(gulp.dest('wwwroot/app'));
});
```

**Comment by asartem** [comment] 2017-01-29 21:53
gulp-uglify and gulp-sourcemap dont' work together correctly on typescript  (angular 2) files.
I hade to disabled gulp-uglify. But the bug can be in gulp-sourcemap.

**Comment by phated** [comment] 2017-03-13 22:29
Closing this as a duplicate of one of the many issues about typescript.

**Closed by phated** 2017-03-13 22:29 UTC
