### ISSUE TITLE
How to generate sourcemap that contains relative 'sources' and 'files', as tsc does?

### ISSUE THREAD

**Issue by Yaojian** [floridoo/gulp-sourcemaps#174] opened 2015-12-14 03:13 UTC
I am building a typescript nodejs project using VSCode.

The gulp code is:

```
var tsProject = ts.createProject(tsConfigFile);
  return tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(ts(tsProject))
    .js
    .pipe(sourcemaps.write('.', {includeContent: false, sourceRoot: ''})) 
    .pipe(gulp.dest('.'));
```

For files in subdirectories, such as `routes/users.ts`,  the content of the generated `users.js.map` is

```
{"version":3,"sources":["routes/users.ts"],"names":[], "mappings":"...","file":"routes/users.js","sourceRoot":""}
```

The breakpoint is not working in VSCode, so I tried to use `tsc` to generate the sourcemap. The sourcemap generated by `tsc` is

```
{"version":3,"file":"users.js","sourceRoot":"","sources":["users.ts"],"names":[], "mappings":"..."}
```

and it works fine in VSCode.

So how to config gulp-sourcemaps to generate the sourcemap as the `tsc` does?

**Comment by idarous** [comment] 2016-02-17 10:18
I have the same problem. If someone find a solution, please tell me.

**Comment by MikeJerred** [comment] 2016-03-10 20:17
I have this same issue, in the readme it says:

> Example (relative path):
> 
>     gulp.task('javascript', function() {
>       var stream = gulp.src('src/**/*.js')
>         .pipe(sourcemaps.init())
>           .pipe(plugin1())
>           .pipe(plugin2())
>         .pipe(sourcemaps.write('.', {includeContent: false, sourceRoot: '../src'}))
>         .pipe(gulp.dest('dist'));
>     });
> 
> In this case for a file written to `dist/subdir/example.js`, the source map is written to `dist/subdir/example.js.map` and the sourceRoot will be `../../src` (resulting in the full source path `../../src/subdir/example.js`).

However this doesn't work, it simply produces `"sourceRoot": "../src"` even for nested files.

**Comment by MikeJerred** [comment] 2016-03-10 20:28
I just went into the source to fix this but it's actually done already it's just that v1.6.0 tag doesn't have those commits yet. You can use `"gulp-sourcemaps": "git://github.com/floridoo/gulp-sourcemaps.git#a626896c7660114680ecf998394bda87004c08e1"` in `package.json` for now

**Comment by garethflowers** [comment] 2016-04-07 13:16
I've hit the same issue too (though as @MikeJerred ponted out the master works fine).

Are there plans for a new (1.6.1?) release any time soon?

**Comment by JimmyBoh** [comment] 2016-07-05 20:12
@floridoo Any updates on this? It is plaguing me as well (and I am restricted from using the github repo as an npm package).

**Comment by arashnorouzi** [comment] 2016-07-07 00:56
@floridoo I have same issue, Using node does not allow me to get packages from git hub. Is there any alternate workaround?

**Comment by gravaton** [comment] 2016-07-10 06:41
I have a similar issue, although the differences are a little more troubling - if I write out sourcemaps with the following invocation:

```.pipe(sourcemaps.write('.')```

The sourcemaps have the following at the end:

```"sourceRoot":"/source"```

How this gets there is baffling to me as no such directory is used anywhere in my compilation steps.

**Comment by Emigre** [comment] 2016-07-30 09:31
Duplicate of #163 if I'm not mistaken?

**Comment by stevenvachon** [comment] 2016-08-25 18:19
@floridoo wtf?

**Comment by nmccready** [comment] 2016-12-01 05:36
> I've hit the same issue too (though as @MikeJerred ponted out the master works fine).
> 
> Are there plans for a new (1.6.1?) release any time soon?

This release has happened so is this still a problem?

See here please and then I will have something to work off of.

Also you could produce a spec that compiles tsc output with an expectation to match with the gulp-sourcemaps output. This could be added to test/integration.

**Comment by Nepoxx** [comment] 2017-01-11 21:54
This is what I have and it works with VSCode although the output is not exactly like TSC's output:

```js
return gulp.src(['typings/index.d.ts', 'src/**/*.ts'])
    .pipe(sourcemaps.init())
    .pipe(tsProject(ts.reporter.longReporter()))
    .js
    .pipe(sourcemaps.write({
      mapSources: (path) => path, // This affects the "sources" attribute even if it is a no-op. I don't know why.
      sourceRoot: (file) => {
        return path.relative(file.relative, path.join(file.cwd, 'src'));
      }
    }))
    .pipe(gulp.dest('dist'));
```

**Comment by phated** [comment] 2017-03-13 22:06
As @Emigre said, this reads like a duplicate of #163 - Closing in favor of that.

**Closed by phated** 2017-03-13 22:06 UTC
