### ISSUE TITLE
Source maps not generated correctly

### ISSUE THREAD

**Issue by MikeCheel** [floridoo/gulp-sourcemaps#204] opened 2016-06-09 18:42 UTC
The source maps generated from this plugin are not identical to the ones emitted from the typescript compiler and are causing my web storm debugger to fail when I generate them from this plugin. 

For example, comparing the two files that bring me to submit this issue I find that the one that works has 2165 characters and the one that doesn't work has 2175.

**Comment by JimmyBoh** [comment] 2016-07-05 20:06
I am have a similar experience. I have a TypeScript project with each file being compiled in place with external map files (`.js` and `.js.map` are compiled next to `.ts` files).

When using the TypeScript compiler the map files have `"sources": ["my-component.ts"]` and `"file": "my-component.js"`, whereas this plugin used with `gulp-typescript` results in more complex paths for both fields (something like `Apps/app-one/my-component/my-component.ts`, etc).

Is this just a setting I am missing? Is this something it cannot handle? I've tried a bunch of configurations but cannot figure it out.

**Comment by JimmyBoh** [comment] 2016-07-05 20:07
@MikeCheel @floridoo Could this issue be renamed to "Source maps differ from Typescript source maps"?

**Comment by JimmyBoh** [comment] 2016-07-05 20:09
Possible duplicate of #174.

**Comment by nmccready** [comment] 2016-12-01 05:16
Not enough information and deferring to #174

**Closed by nmccready** 2016-12-01 05:16 UTC
